CREATE TABLE USER (
	USER_ID VARCHAR(100) PRIMARY KEY
);
COMMIT;

CREATE TABLE URL (
	URL_ID IDENTITY PRIMARY KEY,
	USER_ID_FK VARCHAR(100) NOT NULL,
	URL VARCHAR(3200)  NOT NULL,
	SHORT_URL VARCHAR(3200)  NOT NULL,
	HITS INTEGER  NOT NULL 
);
COMMIT;

ALTER TABLE URL
ADD FOREIGN KEY (USER_ID_FK) 
REFERENCES USER(USER_ID);
COMMIT;